name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env: #globales
    NODE_VERSION: "22.21.1"
    APP_NAME: "cron-ticker-v2"

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            BUILD_DIR: dist

        steps:
            - uses: actions/checkout@v4

            - name: show variables
              run: |
                echo "APP: ${{ env.APP_NAME }}"
                echo "NODE: ${{ env.NODE_VERSION }}"
                
