name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: "22.21.1"
  APP_NAME: "cron-ticker-v2"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: dist

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: show variables
        run: |
          echo "APP: ${{ env.APP_NAME }}"
          echo "NODE: ${{ env.NODE_VERSION }}"

      - name: show github variables
        run: |
          echo "APP: ${{ vars.APP_VERSION }}"
      - name: show github Secrets
        run: |
          echo "Secret: ${{secrets.API_KEY}}"

      - name: show github Functions
        run: |
          echo "${{toJson(github)}}"

      - name: Build
        run: npm run build
        env:
          APP_VERSION: ${{ vars.APP_VERSION }}